// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://vbiffxkelyzykueprvfm.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZiaWZmeGtlbHl6eWt1ZXBydmZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI5OTQyOTMsImV4cCI6MjA0ODU3MDI5M30.In4uNOqvx56pfkMnQEENwooMVm_fasmYQ13PFJDtBAE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);